import {
  PlacementDriveStatus,
  EmploymentType,
  ApplicationStatus,
  QuestionDifficulty,
  QuizStatus,
  AttemptStatus,
  PrepCategory,
} from "@prisma/client";

export interface DemoCompany {
  id: string;
  name: string;
  slug: string;
  website: string;
  industry: string;
  logoUrl: string;
  description: string;
  location: string;
  companySize: string;
  contactPerson: string;
  contactEmail: string;
  contactPhone: string;
  createdAt: string;
  updatedAt: string;
}

export interface DemoPlacementDrive {
  id: string;
  companyId: string;
  companyName: string;
  companyLogo: string;
  title: string;
  slug: string;
  role: string;
  employmentType: EmploymentType;
  location: string;
  packageMin: number;
  packageMax: number;
  currency: string;
  description: string;
  applicationDeadline: string;
  driveDate?: string | null;
  status: PlacementDriveStatus;
  minCgpa: number;
  maxBacklogs: number;
  allowedDepartments: string[];
  allowedSemesters: number[];
  requiredSkills: string[];
  batchCriteria?: string | null;
  bondDetails?: string | null;
  selectionRounds: string[];
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface DemoApplicationStatusHistory {
  id: string;
  applicationId: string;
  oldStatus: ApplicationStatus | null;
  newStatus: ApplicationStatus;
  changedBy: string;
  changerName: string;
  remarks: string | null;
  createdAt: string;
}

export interface DemoPlacementApplication {
  id: string;
  driveId: string;
  driveTitle: string;
  companyName: string;
  companyLogo: string;
  studentId: string;
  studentUserId: string;
  studentName: string;
  studentEmail: string;
  rollNumber: string;
  departmentName: string;
  semester: number;
  cgpa: number;
  activeBacklogs: number;
  resumeUrl: string;
  status: ApplicationStatus;
  remarks?: string | null;
  appliedAt: string;
  updatedAt: string;
  statusHistory: DemoApplicationStatusHistory[];
}

export interface DemoPrepQuestion {
  id: string;
  category: PrepCategory;
  question: string;
  options: string[];
  correctOptionIndex: number;
  explanation: string;
  difficulty: QuestionDifficulty;
  topic: string;
  marks: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface DemoQuiz {
  id: string;
  title: string;
  slug: string;
  category: PrepCategory;
  durationSeconds: number;
  questionCount: number;
  totalMarks: number;
  passingMarks: number;
  status: QuizStatus;
  questionIds: string[];
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface DemoQuizAnswer {
  questionId: string;
  selectedOptionIndex: number | null;
  isCorrect: boolean;
  marksAwarded: number;
}

export interface DemoQuizAttempt {
  id: string;
  quizId: string;
  quizTitle: string;
  quizCategory: PrepCategory;
  studentId: string;
  studentUserId: string;
  studentName: string;
  status: AttemptStatus;
  startedAt: string;
  expiresAt: string;
  submittedAt?: string | null;
  score: number;
  percentage: number;
  passed: boolean;
  totalCorrect: number;
  totalIncorrect: number;
  totalUnanswered: number;
  timeTakenSeconds: number;
  answers: Record<string, number | null>; // questionId -> selectedIndex
  detailedAnswers?: DemoQuizAnswer[];
  createdAt: string;
  updatedAt: string;
}

// ==========================================
// 12 DEMO COMPANIES
// ==========================================
export const DEMO_COMPANIES: DemoCompany[] = [
  {
    id: "comp-001",
    name: "Google India",
    slug: "google-india",
    website: "https://careers.google.com",
    industry: "Internet & Technology",
    logoUrl: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=300&q=80",
    description: "Multinational technology company focusing on artificial intelligence, search engine, cloud computing, software, and hardware.",
    location: "Bangalore & Hyderabad",
    companySize: "10,000+",
    contactPerson: "Pooja Hegde (University Recruiting)",
    contactEmail: "campus-recruitment@google.com",
    contactPhone: "+91 80 6721 8000",
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "comp-002",
    name: "Microsoft IDC",
    slug: "microsoft-idc",
    website: "https://careers.microsoft.com",
    industry: "Software & Cloud",
    logoUrl: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=300&q=80",
    description: "Empowering every person and organization on the planet to achieve more through Azure, Developer Tools, and AI platforms.",
    location: "Hyderabad & Bangalore",
    companySize: "10,000+",
    contactPerson: "Kunal Bansal (Talent Acquisition)",
    contactEmail: "idc-campus@microsoft.com",
    contactPhone: "+91 40 6695 0000",
    createdAt: "2026-01-11T10:00:00.000Z",
    updatedAt: "2026-01-11T10:00:00.000Z",
  },
  {
    id: "comp-003",
    name: "Amazon Development Centre",
    slug: "amazon-india",
    website: "https://amazon.jobs",
    industry: "E-Commerce & Cloud Computing",
    logoUrl: "https://images.unsplash.com/photo-1523474255658-4af61b1614ff?w=300&q=80",
    description: "Global e-commerce and cloud computing giant driving customer obsession, operational excellence, and scalable services.",
    location: "Bangalore, Chennai & Hyderabad",
    companySize: "10,000+",
    contactPerson: "Rohan Iyer (University Relations)",
    contactEmail: "in-campus-jobs@amazon.com",
    contactPhone: "+91 80 4153 1000",
    createdAt: "2026-01-12T11:00:00.000Z",
    updatedAt: "2026-01-12T11:00:00.000Z",
  },
  {
    id: "comp-004",
    name: "Tata Consultancy Services",
    slug: "tcs",
    website: "https://www.tcs.com",
    industry: "IT Services & Consulting",
    logoUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&q=80",
    description: "Leading global IT services, consulting, and business solutions organization transforming business through technology innovation.",
    location: "Mumbai, Pune & PAN India",
    companySize: "50,000+",
    contactPerson: "Deepak Sharma (Campus Placement Head)",
    contactEmail: "campus.connect@tcs.com",
    contactPhone: "+91 22 6778 9999",
    createdAt: "2026-01-13T09:30:00.000Z",
    updatedAt: "2026-01-13T09:30:00.000Z",
  },
  {
    id: "comp-005",
    name: "Goldman Sachs",
    slug: "goldman-sachs",
    website: "https://www.goldmansachs.com/careers",
    industry: "Financial Services & Investment Banking",
    logoUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=300&q=80",
    description: "Global investment banking, securities and investment management firm delivering innovative financial engineering and software platforms.",
    location: "Bangalore & Hyderabad",
    companySize: "5,000 - 10,000",
    contactPerson: "Shweta Kulkarni (Human Capital)",
    contactEmail: "campus-asia@gs.com",
    contactPhone: "+91 80 4127 8000",
    createdAt: "2026-01-14T14:00:00.000Z",
    updatedAt: "2026-01-14T14:00:00.000Z",
  },
  {
    id: "comp-006",
    name: "Cisco Systems",
    slug: "cisco-systems",
    website: "https://jobs.cisco.com",
    industry: "Networking & Cybersecurity",
    logoUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=300&q=80",
    description: "Worldwide leader in networking technology, secure internet backbones, multi-cloud connectivity, and cybersecurity solutions.",
    location: "Bangalore",
    companySize: "10,000+",
    contactPerson: "Vikram Sen (Talent Lead)",
    contactEmail: "university-india@cisco.com",
    contactPhone: "+91 80 4426 0000",
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "comp-007",
    name: "Oracle India",
    slug: "oracle-india",
    website: "https://www.oracle.com/careers",
    industry: "Database & Enterprise Cloud",
    logoUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300&q=80",
    description: "Enterprise software solutions, autonomous cloud databases, high-performance infrastructure, and business applications.",
    location: "Bangalore & Hyderabad",
    companySize: "10,000+",
    contactPerson: "Ananya Rao (College Relations)",
    contactEmail: "campus-in@oracle.com",
    contactPhone: "+91 80 4108 5000",
    createdAt: "2026-01-16T11:00:00.000Z",
    updatedAt: "2026-01-16T11:00:00.000Z",
  },
  {
    id: "comp-008",
    name: "Deloitte USI",
    slug: "deloitte-usi",
    website: "https://www2.deloitte.com/ui/en/careers",
    industry: "Management Consulting & Audit",
    logoUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=300&q=80",
    description: "Global consulting and enterprise risk services leader offering strategy, analytics, cyber risk, and tech architecture.",
    location: "Hyderabad, Mumbai, Bangalore & Gurgaon",
    companySize: "10,000+",
    contactPerson: "Siddharth Verma (Campus Lead)",
    contactEmail: "deloitte-campus@deloitte.com",
    contactPhone: "+91 40 6762 1000",
    createdAt: "2026-01-17T12:00:00.000Z",
    updatedAt: "2026-01-17T12:00:00.000Z",
  },
  {
    id: "comp-009",
    name: "Qualcomm India",
    slug: "qualcomm-india",
    website: "https://www.qualcomm.com/company/careers",
    industry: "Semiconductors & Telecommunications",
    logoUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&q=80",
    description: "World leader in next-generation wireless technologies, 5G chipsets, compute processors, and embedded device architecture.",
    location: "Hyderabad & Bangalore",
    companySize: "5,000 - 10,000",
    contactPerson: "Gautam Nair (Engineering Recruitment)",
    contactEmail: "india-university@qualcomm.com",
    contactPhone: "+91 40 6608 0000",
    createdAt: "2026-01-18T10:00:00.000Z",
    updatedAt: "2026-01-18T10:00:00.000Z",
  },
  {
    id: "comp-010",
    name: "Razorpay",
    slug: "razorpay",
    website: "https://razorpay.com/jobs",
    industry: "Fintech & Payments",
    logoUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=300&q=80",
    description: "Full-stack financial services platform revolutionizing online payments, neo-banking, payroll, and merchant settlements.",
    location: "Bangalore",
    companySize: "1,000 - 5,000",
    contactPerson: "Neha Kapoor (Tech Recruiting)",
    contactEmail: "careers-campus@razorpay.com",
    contactPhone: "+91 80 4666 9999",
    createdAt: "2026-01-19T09:00:00.000Z",
    updatedAt: "2026-01-19T09:00:00.000Z",
  },
  {
    id: "comp-011",
    name: "ZS Associates",
    slug: "zs-associates",
    website: "https://www.zs.com/careers",
    industry: "Management Consulting & Data Science",
    logoUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=300&q=80",
    description: "Management consulting and technology firm delivering business transformations, pharmaceutical analytics, and healthcare data engines.",
    location: "Pune & Gurgaon",
    companySize: "5,000 - 10,000",
    contactPerson: "Aditya Roy (Campus Lead)",
    contactEmail: "campus-recruitment@zs.com",
    contactPhone: "+91 20 6649 0000",
    createdAt: "2026-01-20T10:00:00.000Z",
    updatedAt: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "comp-012",
    name: "Tesla India R&D",
    slug: "tesla-india",
    website: "https://www.tesla.com/careers",
    industry: "Electric Vehicles & Clean Energy",
    logoUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=300&q=80",
    description: "Accelerating the world's transition to sustainable energy through electric vehicles, autonomous robotics, and grid-scale storage.",
    location: "Pune & Bangalore",
    companySize: "1,000 - 5,000",
    contactPerson: "Marcus Vance (Global University Staffing)",
    contactEmail: "campus-india@tesla.com",
    contactPhone: "+91 20 7100 1100",
    createdAt: "2026-01-21T15:00:00.000Z",
    updatedAt: "2026-01-21T15:00:00.000Z",
  },
];

// ==========================================
// 14 DEMO PLACEMENT DRIVES
// ==========================================
export const DEMO_DRIVES: DemoPlacementDrive[] = [
  {
    id: "drv-001",
    companyId: "comp-001",
    companyName: "Google India",
    companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=300&q=80",
    title: "Software Engineer (University Graduate)",
    slug: "google-swe-grad-2026",
    role: "Software Development Engineer",
    employmentType: EmploymentType.FULL_TIME,
    location: "Bangalore / Hyderabad",
    packageMin: 32.0,
    packageMax: 45.0,
    currency: "INR",
    description: "Build scalable distributed services, search indexing pipelines, and AI systems. We look for strong foundations in algorithms, data structures, and computer science principles.",
    applicationDeadline: "2026-10-30T18:00:00.000Z",
    driveDate: "2026-11-05T09:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 8.5,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["Data Structures", "Algorithms", "C++", "Java", "Distributed Systems"],
    batchCriteria: "2022-2026",
    bondDetails: "No service bond required.",
    selectionRounds: ["Online Coding Assessment", "Technical Interview 1", "Technical Interview 2", "Googliness & Leadership"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-01T09:00:00.000Z",
    updatedAt: "2026-02-01T09:00:00.000Z",
  },
  {
    id: "drv-002",
    companyId: "comp-002",
    companyName: "Microsoft IDC",
    companyLogo: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=300&q=80",
    title: "Software Engineer - Azure Cloud Core",
    slug: "microsoft-azure-sde-2026",
    role: "Software Engineer",
    employmentType: EmploymentType.FULL_TIME,
    location: "Hyderabad",
    packageMin: 28.0,
    packageMax: 42.0,
    currency: "INR",
    description: "Join Azure Cloud Infrastructure engineering teams. Design resilient hyper-scale distributed services, telemetry pipelines, and virtualization substrates.",
    applicationDeadline: "2026-11-05T18:00:00.000Z",
    driveDate: "2026-11-12T09:30:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 8.0,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology", "Electronics & Telecommunication"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["C#", "C++", "Cloud Computing", "OS Concepts", "System Design"],
    batchCriteria: "2022-2026",
    bondDetails: "No service bond required.",
    selectionRounds: ["Online Aptitude & Coding", "Technical Round 1", "Technical Round 2", "Director Round"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-02T10:00:00.000Z",
    updatedAt: "2026-02-02T10:00:00.000Z",
  },
  {
    id: "drv-003",
    companyId: "comp-003",
    companyName: "Amazon Development Centre",
    companyLogo: "https://images.unsplash.com/photo-1523474255658-4af61b1614ff?w=300&q=80",
    title: "Software Development Engineer (SDE-1)",
    slug: "amazon-sde1-2026",
    role: "SDE-1",
    employmentType: EmploymentType.FULL_TIME,
    location: "Bangalore",
    packageMin: 26.0,
    packageMax: 38.0,
    currency: "INR",
    description: "Work on customer-facing architectures powering Prime, AWS, and retail catalog infrastructure. Apply Leadership Principles while delivering high-throughput code.",
    applicationDeadline: "2026-10-25T20:00:00.000Z",
    driveDate: "2026-11-02T10:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 7.5,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["Java", "OOP", "DBMS", "Microservices", "REST APIs"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Online Assessment (Coding + Work Styles)", "Technical Interview 1", "Technical Interview 2", "Bar Raiser"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-03T11:00:00.000Z",
    updatedAt: "2026-02-03T11:00:00.000Z",
  },
  {
    id: "drv-004",
    companyId: "comp-005",
    companyName: "Goldman Sachs",
    companyLogo: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=300&q=80",
    title: "Quantitative Analytics & Engineering Associate",
    slug: "goldman-sachs-quant-2026",
    role: "Quantitative Analyst",
    employmentType: EmploymentType.FULL_TIME,
    location: "Bangalore",
    packageMin: 30.0,
    packageMax: 40.0,
    currency: "INR",
    description: "High-frequency pricing models, algorithmic trading infrastructure, and quantitative risk management platforms for global investment divisions.",
    applicationDeadline: "2026-11-15T18:00:00.000Z",
    driveDate: "2026-11-22T09:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 9.0, // Strict: Demo student (8.74) is NOT eligible
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["Probability", "Linear Algebra", "C++", "Python", "Financial Markets"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Aptitude & Math Screener", "Coding Assessment", "Quant Technical Round", "Partner Fit"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-04T09:00:00.000Z",
    updatedAt: "2026-02-04T09:00:00.000Z",
  },
  {
    id: "drv-005",
    companyId: "comp-009",
    companyName: "Qualcomm India",
    companyLogo: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&q=80",
    title: "Embedded Systems & Firmware Engineer",
    slug: "qualcomm-embedded-firmware-2026",
    role: "Embedded Systems Engineer",
    employmentType: EmploymentType.FULL_TIME,
    location: "Hyderabad",
    packageMin: 20.0,
    packageMax: 28.0,
    currency: "INR",
    description: "Low-level driver development, RTOS kernel integration, modem protocols, and SoC validation for Snapdragon mobile platforms.",
    applicationDeadline: "2026-11-10T18:00:00.000Z",
    driveDate: "2026-11-18T10:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 8.0,
    maxBacklogs: 0,
    allowedDepartments: ["Electronics & Telecommunication"], // Strict: Comp Engg student is NOT eligible
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["Embedded C", "Microcontrollers", "RTOS", "Computer Architecture"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Written Hardware & C Test", "Technical Interview 1", "Technical Interview 2", "HR"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-05T14:00:00.000Z",
    updatedAt: "2026-02-05T14:00:00.000Z",
  },
  {
    id: "drv-006",
    companyId: "comp-010",
    companyName: "Razorpay",
    companyLogo: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=300&q=80",
    title: "Full-Stack Software Engineer (Frontend Focus)",
    slug: "razorpay-fullstack-2026",
    role: "Product Engineer",
    employmentType: EmploymentType.FULL_TIME,
    location: "Bangalore",
    packageMin: 18.0,
    packageMax: 26.0,
    currency: "INR",
    description: "Architect secure financial checkout experiences, banking dashboard micro-frontends, and highly accessible React components.",
    applicationDeadline: "2026-11-20T18:00:00.000Z",
    driveDate: "2026-11-28T10:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 7.5,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["TypeScript", "Next.js", "React", "Node.js", "PostgreSQL"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Frontend Machine Coding", "Architecture Discussion", "Hiring Manager Round"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-06T10:00:00.000Z",
    updatedAt: "2026-02-06T10:00:00.000Z",
  },
  {
    id: "drv-007",
    companyId: "comp-006",
    companyName: "Cisco Systems",
    companyLogo: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=300&q=80",
    title: "Cloud & Network Security Engineer",
    slug: "cisco-cloud-security-2026",
    role: "Security Engineer",
    employmentType: EmploymentType.FULL_TIME,
    location: "Bangalore",
    packageMin: 17.5,
    packageMax: 24.0,
    currency: "INR",
    description: "Develop enterprise zero-trust security appliances, firewall inspection engines, and cloud posture management software.",
    applicationDeadline: "2026-11-25T18:00:00.000Z",
    driveDate: "2026-12-02T09:30:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 7.0,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology", "Electronics & Telecommunication"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["Computer Networks", "Cybersecurity", "Python", "Linux", "Docker"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Online Aptitude + Networking Test", "Technical Interview", "Managerial Round"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-07T11:00:00.000Z",
    updatedAt: "2026-02-07T11:00:00.000Z",
  },
  {
    id: "drv-008",
    companyId: "comp-004",
    companyName: "Tata Consultancy Services",
    companyLogo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&q=80",
    title: "TCS Digital - Software Specialist",
    slug: "tcs-digital-2026",
    role: "System Engineer (Digital Cadre)",
    employmentType: EmploymentType.FULL_TIME,
    location: "Mumbai / Pune",
    packageMin: 7.5,
    packageMax: 9.0,
    currency: "INR",
    description: "Enterprise software engineering across global clients in banking, retail, and manufacturing. Working with cloud, automation, and full-stack frameworks.",
    applicationDeadline: "2026-12-01T20:00:00.000Z",
    driveDate: "2026-12-10T09:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 7.0,
    maxBacklogs: 1,
    allowedDepartments: ["Computer Engineering", "Information Technology", "Electronics & Telecommunication", "Mechanical Engineering"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["Java", "Python", "SQL", "Problem Solving"],
    batchCriteria: "2022-2026",
    bondDetails: "1 Year Service Commitment",
    selectionRounds: ["TCS NQT Advanced Test", "Technical + MR + HR Interview"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-08T09:00:00.000Z",
    updatedAt: "2026-02-08T09:00:00.000Z",
  },
  {
    id: "drv-009",
    companyId: "comp-008",
    companyName: "Deloitte USI",
    companyLogo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=300&q=80",
    title: "Analyst - Cloud & Technology Advisory",
    slug: "deloitte-analyst-tech-2026",
    role: "Technology Analyst",
    employmentType: EmploymentType.FULL_TIME,
    location: "Hyderabad",
    packageMin: 8.5,
    packageMax: 11.5,
    currency: "INR",
    description: "Advising Fortune 500 corporations on enterprise cloud transitions, ERP architectures, and process automation frameworks.",
    applicationDeadline: "2026-11-18T18:00:00.000Z",
    driveDate: "2026-11-26T10:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 6.5,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology", "Electronics & Telecommunication"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["Business Analytics", "SQL", "Cloud Basics", "Communication"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Cognitive & Technical Assessment", "Case Study Discussion", "Partner Interview"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-09T14:00:00.000Z",
    updatedAt: "2026-02-09T14:00:00.000Z",
  },
  {
    id: "drv-010",
    companyId: "comp-011",
    companyName: "ZS Associates",
    companyLogo: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=300&q=80",
    title: "Business Technology Solutions Associate (BTSA)",
    slug: "zs-btsa-2026",
    role: "Technology Consultant",
    employmentType: EmploymentType.FULL_TIME,
    location: "Pune",
    packageMin: 13.5,
    packageMax: 16.0,
    currency: "INR",
    description: "Build business intelligence dashboards, commercial data pipelines, and analytics algorithms for healthcare clients worldwide.",
    applicationDeadline: "2026-12-05T18:00:00.000Z",
    driveDate: "2026-12-14T09:00:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 7.0,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology", "Electronics & Telecommunication"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["SQL", "Python", "Data Warehousing", "Business Problem Solving"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Online Aptitude + Video Case", "Case Debrief Round", "Fit Interview"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-10T10:00:00.000Z",
    updatedAt: "2026-02-10T10:00:00.000Z",
  },
  {
    id: "drv-011",
    companyId: "comp-007",
    companyName: "Oracle India",
    companyLogo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300&q=80",
    title: "Associate Systems Engineer - OCI Core",
    slug: "oracle-oci-systems-2026",
    role: "Systems Engineer",
    employmentType: EmploymentType.FULL_TIME,
    location: "Bangalore",
    packageMin: 18.0,
    packageMax: 24.0,
    currency: "INR",
    description: "Low-level system programming for Oracle Cloud Infrastructure hypervisors, storage clusters, and high-speed SDN interconnects.",
    applicationDeadline: "2026-12-10T18:00:00.000Z",
    driveDate: "2026-12-20T09:30:00.000Z",
    status: PlacementDriveStatus.PUBLISHED,
    minCgpa: 7.8,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["C", "C++", "Linux Internals", "Networking", "Database Systems"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Coding & CS Fundamentals", "Technical Round 1", "Technical Round 2", "HR"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-11T11:00:00.000Z",
    updatedAt: "2026-02-11T11:00:00.000Z",
  },
  {
    id: "drv-012",
    companyId: "comp-001",
    companyName: "Google India",
    companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=300&q=80",
    title: "Summer Technical Intern 2026 (STEP)",
    slug: "google-step-intern-2026",
    role: "Software Engineering Intern",
    employmentType: EmploymentType.INTERNSHIP,
    location: "Bangalore",
    packageMin: 12.0, // Equivalent annual stipend
    packageMax: 15.0,
    currency: "INR",
    description: "3-month summer engineering internship for pre-final year students to work on real-world production projects alongside Google mentor engineers.",
    applicationDeadline: "2026-09-01T18:00:00.000Z", // Past deadline
    driveDate: "2026-09-15T09:00:00.000Z",
    status: PlacementDriveStatus.APPLICATION_CLOSED,
    minCgpa: 7.5,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology"],
    allowedSemesters: [5, 6],
    requiredSkills: ["Data Structures", "Algorithms", "Python", "Java"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Coding Screener", "Technical Interview 1", "Technical Interview 2"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-12T09:00:00.000Z",
    updatedAt: "2026-02-12T09:00:00.000Z",
  },
  {
    id: "drv-013",
    companyId: "comp-012",
    companyName: "Tesla India R&D",
    companyLogo: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=300&q=80",
    title: "Autopilot Vision & Robotics Engineer (Upcoming)",
    slug: "tesla-autopilot-robotics-2026",
    role: "Robotics Engineer",
    employmentType: EmploymentType.FULL_TIME,
    location: "Pune",
    packageMin: 25.0,
    packageMax: 35.0,
    currency: "INR",
    description: "Draft opportunity: Building perception pipelines, optical flow models, and embedded control modules for robotics platforms.",
    applicationDeadline: "2026-12-25T18:00:00.000Z",
    driveDate: null,
    status: PlacementDriveStatus.DRAFT, // Hidden from students
    minCgpa: 8.5,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology", "Mechanical Engineering"],
    allowedSemesters: [6, 7, 8],
    requiredSkills: ["PyTorch", "C++", "Computer Vision", "ROS"],
    batchCriteria: "2022-2026",
    bondDetails: "None",
    selectionRounds: ["Take-home Vision Challenge", "Technical Round", "Executive Interview"],
    createdBy: "demo-placement-001",
    createdAt: "2026-02-13T10:00:00.000Z",
    updatedAt: "2026-02-13T10:00:00.000Z",
  },
  {
    id: "drv-014",
    companyId: "comp-004",
    companyName: "Tata Consultancy Services",
    companyLogo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&q=80",
    title: "TCS Innovator Research Intern",
    slug: "tcs-innovator-intern-2026",
    role: "Research Intern",
    employmentType: EmploymentType.INTERNSHIP,
    location: "Pune",
    packageMin: 5.0,
    packageMax: 6.0,
    currency: "INR",
    description: "Archived recruitment drive from last semester.",
    applicationDeadline: "2025-12-01T18:00:00.000Z",
    driveDate: "2025-12-15T09:00:00.000Z",
    status: PlacementDriveStatus.ARCHIVED,
    minCgpa: 7.0,
    maxBacklogs: 0,
    allowedDepartments: ["Computer Engineering", "Information Technology"],
    allowedSemesters: [5, 6],
    requiredSkills: ["Python", "Machine Learning"],
    batchCriteria: "2021-2025",
    bondDetails: "None",
    selectionRounds: ["Research Paper Review", "Interview"],
    createdBy: "demo-placement-001",
    createdAt: "2025-10-01T09:00:00.000Z",
    updatedAt: "2025-12-20T09:00:00.000Z",
  },
];

// ==========================================
// PRE-SEEDED APPLICATIONS (Multi-stage)
// ==========================================
export const DEMO_APPLICATIONS: DemoPlacementApplication[] = [
  {
    id: "app-001",
    driveId: "drv-002",
    driveTitle: "Software Engineer - Azure Cloud Core",
    companyName: "Microsoft IDC",
    companyLogo: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=300&q=80",
    studentId: "STU-2022-0101",
    studentUserId: "demo-student-001",
    studentName: "Aarav Mehta",
    studentEmail: "student@campusconnect.edu",
    rollNumber: "22COMPA101",
    departmentName: "Computer Engineering",
    semester: 6,
    cgpa: 8.74,
    activeBacklogs: 0,
    resumeUrl: "https://campusconnect.edu/resumes/aarav-mehta-swe-2026.pdf",
    status: ApplicationStatus.SHORTLISTED,
    remarks: "Cleared initial screening with high CGPA. Scheduled for Technical Round 1 on Nov 12.",
    appliedAt: "2026-02-05T14:30:00.000Z",
    updatedAt: "2026-02-08T11:00:00.000Z",
    statusHistory: [
      {
        id: "hist-001",
        applicationId: "app-001",
        oldStatus: null,
        newStatus: ApplicationStatus.APPLIED,
        changedBy: "demo-student-001",
        changerName: "Aarav Mehta (Student)",
        remarks: "Submitted formal application for Azure Cloud Core role.",
        createdAt: "2026-02-05T14:30:00.000Z",
      },
      {
        id: "hist-002",
        applicationId: "app-001",
        oldStatus: ApplicationStatus.APPLIED,
        newStatus: ApplicationStatus.SHORTLISTED,
        changedBy: "demo-placement-001",
        changerName: "Vikramaditya Nair (Placement Officer)",
        remarks: "Cleared academic resume screening. Candidate matches C# and Cloud criteria.",
        createdAt: "2026-02-08T11:00:00.000Z",
      },
    ],
  },
  {
    id: "app-002",
    driveId: "drv-008",
    driveTitle: "TCS Digital - Software Specialist",
    companyName: "Tata Consultancy Services",
    companyLogo: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&q=80",
    studentId: "STU-2022-0101",
    studentUserId: "demo-student-001",
    studentName: "Aarav Mehta",
    studentEmail: "student@campusconnect.edu",
    rollNumber: "22COMPA101",
    departmentName: "Computer Engineering",
    semester: 6,
    cgpa: 8.74,
    activeBacklogs: 0,
    resumeUrl: "https://campusconnect.edu/resumes/aarav-mehta-swe-2026.pdf",
    status: ApplicationStatus.APPLIED,
    remarks: "Application received and registered for TCS Digital on-campus drive.",
    appliedAt: "2026-02-10T16:00:00.000Z",
    updatedAt: "2026-02-10T16:00:00.000Z",
    statusHistory: [
      {
        id: "hist-003",
        applicationId: "app-002",
        oldStatus: null,
        newStatus: ApplicationStatus.APPLIED,
        changedBy: "demo-student-001",
        changerName: "Aarav Mehta (Student)",
        remarks: "Applied to TCS Digital.",
        createdAt: "2026-02-10T16:00:00.000Z",
      },
    ],
  },
];

// ==========================================
// 52 PREPARATION QUESTIONS (Detailed)
// ==========================================
export const DEMO_PREP_QUESTIONS: DemoPrepQuestion[] = [
  // --- QUANTITATIVE APTITUDE (10) ---
  {
    id: "pq-001",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "A pipe can fill a tank in 12 hours and another pipe can empty it in 18 hours. If both pipes are opened together, how many hours will it take to fill the tank?",
    options: ["24 hours", "30 hours", "36 hours", "42 hours"],
    correctOptionIndex: 2,
    explanation: "Net filling rate per hour = (1/12) - (1/18) = (3 - 2)/36 = 1/36. Therefore, the tank fills completely in 36 hours.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Pipes & Cisterns",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-002",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "A train running at 72 km/h crosses a 260 m long platform in 23 seconds. What is the length of the train?",
    options: ["180 meters", "200 meters", "220 meters", "240 meters"],
    correctOptionIndex: 1,
    explanation: "Speed = 72 * (5/18) = 20 m/s. Total distance in 23s = 20 * 23 = 460 m. Train length = Total distance - Platform length = 460 - 260 = 200 meters.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Time, Speed & Distance",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-003",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "By selling an article for ₹720, a shopkeeper loses 10%. At what price should he sell it to gain 15%?",
    options: ["₹840", "₹900", "₹920", "₹960"],
    correctOptionIndex: 2,
    explanation: "Cost Price = 720 / 0.90 = ₹800. For 15% profit: Selling Price = 800 * 1.15 = ₹920.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Profit & Loss",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-004",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "The ratio of ages of two friends is 4:5. After 6 years, the ratio becomes 5:6. What is the sum of their present ages?",
    options: ["45 years", "54 years", "60 years", "72 years"],
    correctOptionIndex: 1,
    explanation: "Let ages be 4x and 5x. (4x + 6)/(5x + 6) = 5/6 => 24x + 36 = 25x + 30 => x = 6. Present ages = 24 and 30. Sum = 54 years.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Ratios & Proportions",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-005",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "In how many different ways can the letters of the word 'CAMPUS' be arranged such that vowels always come together?",
    options: ["120", "240", "480", "720"],
    correctOptionIndex: 1,
    explanation: "Vowels are A, U (2 vowels). Group them as 1 entity (AU). Total entities to arrange = 4 consonants + 1 group = 5! = 120. Vowels can arrange among themselves in 2! = 2 ways. Total = 120 * 2 = 240 ways.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Permutations & Combinations",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-006",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "Two dice are rolled simultaneously. What is the probability that the sum of the numbers is a prime number?",
    options: ["5/12", "7/18", "15/36", "17/36"],
    correctOptionIndex: 0,
    explanation: "Primes possible between 2 and 12 are 2, 3, 5, 7, 11. Sum 2: 1 pair. Sum 3: 2 pairs. Sum 5: 4 pairs. Sum 7: 6 pairs. Sum 11: 2 pairs. Total favorable outcomes = 1 + 2 + 4 + 6 + 2 = 15. Probability = 15/36 = 5/12.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Probability",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-007",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "A sum of money compounded annually doubles itself in 4 years. In how many years will it become 8 times of itself at the same rate?",
    options: ["8 years", "12 years", "16 years", "20 years"],
    correctOptionIndex: 1,
    explanation: "If P becomes 2P in 4 years, it will become 2^3 = 8P in 3 * 4 = 12 years under compound interest.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Compound Interest",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-008",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "A mixture contains milk and water in the ratio 7:3. If 5 litres of water is added, the ratio becomes 7:5. Find the initial quantity of milk.",
    options: ["14 litres", "17.5 litres", "21 litres", "28 litres"],
    correctOptionIndex: 1,
    explanation: "Let milk be 7x and water be 3x. 7x / (3x + 5) = 7/5 => 35x = 21x + 35 => 14x = 35 => x = 2.5. Milk quantity = 7 * 2.5 = 17.5 litres.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Mixtures & Alligations",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-009",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "A and B can complete a work in 10 and 15 days respectively. They work together for 3 days and then B leaves. In how many more days will A finish the remaining work?",
    options: ["4 days", "5 days", "6 days", "7 days"],
    correctOptionIndex: 1,
    explanation: "Combined rate per day = 1/10 + 1/15 = 5/30 = 1/6. In 3 days, they finish 3 * (1/6) = 1/2 of work. Remaining work = 1/2. Time taken by A alone = (1/2) / (1/10) = 5 days.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Time & Work",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-010",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    question: "Find the unit digit of (7^95 - 3^58).",
    options: ["0", "4", "6", "8"],
    correctOptionIndex: 1,
    explanation: "Cyclicity of 7 is 4: 95 mod 4 = 3 => 7^3 unit digit is 3. Cyclicity of 3 is 4: 58 mod 4 = 2 => 3^2 unit digit is 9. (13 - 9) = 4.",
    difficulty: QuestionDifficulty.HARD,
    topic: "Number Systems",
    marks: 3,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // --- LOGICAL REASONING (10) ---
  {
    id: "pq-011",
    category: PrepCategory.LOGICAL_REASONING,
    question: "Pointing to a photograph of a boy, Suresh said, 'He is the son of the only son of my mother.' How is Suresh related to that boy?",
    options: ["Brother", "Uncle", "Father", "Cousin"],
    correctOptionIndex: 2,
    explanation: "The only son of Suresh's mother is Suresh himself. So the boy is Suresh's son, making Suresh his father.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Blood Relations",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-012",
    category: PrepCategory.LOGICAL_REASONING,
    question: "Find the next number in the series: 3, 7, 15, 31, 63, ?",
    options: ["95", "111", "127", "135"],
    correctOptionIndex: 2,
    explanation: "Each term follows the pattern (2 * current) + 1. So 63 * 2 + 1 = 127.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Number Series",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-013",
    category: PrepCategory.LOGICAL_REASONING,
    question: "If 'MONKEY' is coded as 'XDJMNL', how would 'TIGER' be coded in that same language?",
    options: ["QDFHS", "SDFHS", "SHFDQ", "QDFHN"],
    correctOptionIndex: 0,
    explanation: "The pattern takes the preceding letter of each character from the end to the start. Y-1=X, E-1=D, K-1=J, N-1=M, O-1=N, M-1=L. For TIGER: R-1=Q, E-1=D, G-1=F, I-1=H, T-1=S => QDFHS.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Coding & Decoding",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-014",
    category: PrepCategory.LOGICAL_REASONING,
    question: "Statements: 1. All mangoes are golden. 2. No golden things are cheap. Conclusions: I. All mangoes are cheap. II. Golden mangoes are not cheap.",
    options: ["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"],
    correctOptionIndex: 1,
    explanation: "Since all mangoes are golden, and no golden things are cheap, it logically follows that golden mangoes cannot be cheap. Conclusion II is valid.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Syllogisms",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-015",
    category: PrepCategory.LOGICAL_REASONING,
    question: "A person walks 10 km North, turns right and walks 6 km, then turns right again and walks 10 km. How far and in which direction is he from his starting point?",
    options: ["6 km East", "6 km West", "10 km North", "16 km East"],
    correctOptionIndex: 0,
    explanation: "The North (10 km) and South (10 km) cancel out, leaving a displacement of 6 km towards the East.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Direction Sense",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-016",
    category: PrepCategory.LOGICAL_REASONING,
    question: "In a row of 40 students, Priya is 18th from the left end and Rahul is 15th from the right end. How many students are sitting between them?",
    options: ["7 students", "8 students", "9 students", "10 students"],
    correctOptionIndex: 0,
    explanation: "Total = 40. Students between = 40 - (18 + 15) = 40 - 33 = 7 students.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Order & Ranking",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-017",
    category: PrepCategory.LOGICAL_REASONING,
    question: "Six people P, Q, R, S, T, U sit in a circle facing the center. P is opposite to S. Q is between P and T. R is adjacent to S and U. Who is sitting to the immediate left of P?",
    options: ["Q", "T", "U", "R"],
    correctOptionIndex: 0,
    explanation: "Placing P at top and S opposite at bottom, with Q between P and T, positions Q to the immediate left of P looking toward the center.",
    difficulty: QuestionDifficulty.HARD,
    topic: "Seating Arrangements",
    marks: 3,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-018",
    category: PrepCategory.LOGICAL_REASONING,
    question: "Which of the following does NOT belong to the group: Apple, Orange, Banana, Potato, Mango?",
    options: ["Orange", "Banana", "Potato", "Mango"],
    correctOptionIndex: 2,
    explanation: "Potato is a tuber/vegetable growing underground, whereas all others are botanical fruits growing on trees or plants.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Classification",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-019",
    category: PrepCategory.LOGICAL_REASONING,
    question: "Statement: 'The government should deploy AI-driven traffic lights to reduce city congestion.' Assumptions: I. AI traffic systems can respond dynamically to traffic flow. II. Current static timers cause avoidable bottlenecks.",
    options: ["Only assumption I is implicit", "Only assumption II is implicit", "Both I and II are implicit", "Neither I nor II is implicit"],
    correctOptionIndex: 2,
    explanation: "The recommendation assumes both that static timers cause problems (II) and that AI can adaptively improve flow (I).",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Critical Reasoning",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-020",
    category: PrepCategory.LOGICAL_REASONING,
    question: "Clock: If the time is 3:40 PM, what is the angle between the hour hand and the minute hand?",
    options: ["120 degrees", "130 degrees", "140 degrees", "150 degrees"],
    correctOptionIndex: 1,
    explanation: "Angle = |30 * H - (11/2) * M| = |30 * 3 - (11/2) * 40| = |90 - 220| = 130 degrees.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Clock & Calendar",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // --- VERBAL ABILITY (8) ---
  {
    id: "pq-021",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Choose the word most nearly OPPOSITE in meaning to 'METICULOUS':",
    options: ["Careless", "Methodical", "Accurate", "Cautious"],
    correctOptionIndex: 0,
    explanation: "Meticulous means showing great attention to detail. Careless or sloppy is the exact antonym.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Antonyms",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-022",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Identify the grammatically correct sentence:",
    options: [
      "Neither the manager nor the employees was present in the meeting.",
      "Neither the manager nor the employees were present in the meeting.",
      "Neither the manager or the employees was present in the meeting.",
      "Neither the manager or the employees were present in the meeting.",
    ],
    correctOptionIndex: 1,
    explanation: "With 'Neither... nor...', the verb agrees with the closer subject ('employees', which is plural, so 'were' is correct).",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Subject-Verb Agreement",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-023",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Select the most appropriate SYNONYM for 'PRAGMATIC':",
    options: ["Idealistic", "Practical", "Theoretical", "Fictional"],
    correctOptionIndex: 1,
    explanation: "Pragmatic means dealing with things sensibly and realistically based on practical rather than theoretical considerations.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Synonyms",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-024",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Choose the correct idiom meaning for 'Burn the midnight oil':",
    options: ["Wasting energy unnecessarily", "Working late into the night", "Causing accidental damage", "Cooking dinner late"],
    correctOptionIndex: 1,
    explanation: "'Burn the midnight oil' means to read, study, or work late into the night.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Idioms & Phrases",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-025",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Complete the analogy: EPHEMERAL : PERMANENT :: CANDID : ?",
    options: ["Frank", "Deceptive", "Sincere", "Honest"],
    correctOptionIndex: 1,
    explanation: "Ephemeral and Permanent are antonyms. Candid (open/honest) is the antonym of Deceptive (secretive/dishonest).",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Analogies",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-026",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Detect the error in the sentence: 'Despite of having (A) all qualifications (B), he was rejected (C) without reason (D).'",
    options: ["Part A", "Part B", "Part C", "Part D"],
    correctOptionIndex: 0,
    explanation: "'Despite' never takes the preposition 'of'. It should be 'Despite having' or 'In spite of having'.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Spotting Errors",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-027",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Rearrange the sentences into a coherent paragraph: P: This led to widespread power outages. Q: A fierce thunderstorm struck the city at midnight. R: Trees fell on several major transmission lines. S: Emergency crews worked tirelessly until dawn to restore power.",
    options: ["Q-R-P-S", "Q-P-R-S", "R-P-Q-S", "S-Q-R-P"],
    correctOptionIndex: 0,
    explanation: "The logical order is Storm strikes (Q) -> Trees fall on lines (R) -> Leads to outage (P) -> Crews restore power (S).",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Para Jumbles",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-028",
    category: PrepCategory.VERBAL_ABILITY,
    question: "Select the sentence with correct punctuation:",
    options: [
      "Its crucial that the team updates it's deployment scripts.",
      "It's crucial that the team updates its deployment scripts.",
      "It's crucial that the team updates it's deployment script's.",
      "Its crucial that the team updates its deployment scripts.",
    ],
    correctOptionIndex: 1,
    explanation: "'It's' is the contraction for 'It is', and 'its' is the possessive pronoun for deployment scripts.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Punctuation & Mechanics",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // --- DATA STRUCTURES & ALGORITHMS (10) ---
  {
    id: "pq-029",
    category: PrepCategory.DSA,
    question: "What is the worst-case time complexity of searching for an element in a balanced Binary Search Tree (e.g. AVL or Red-Black Tree)?",
    options: ["O(1)", "O(log N)", "O(N)", "O(N log N)"],
    correctOptionIndex: 1,
    explanation: "Balanced BSTs guarantee height is maintained at O(log N), so lookup, insert, and delete take at most O(log N) operations.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Trees",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-030",
    category: PrepCategory.DSA,
    question: "Which data structure is optimal for implementing a LIFO (Last In First Out) buffer and function call call-stacks?",
    options: ["Queue", "Stack", "Heap", "Hash Table"],
    correctOptionIndex: 1,
    explanation: "A Stack provides O(1) push and pop operations strictly adhering to the LIFO property.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Stacks",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-031",
    category: PrepCategory.DSA,
    question: "In a min-heap with N elements, what is the time complexity to extract the minimum element and restore the heap invariant?",
    options: ["O(1)", "O(log N)", "O(N)", "O(N log N)"],
    correctOptionIndex: 1,
    explanation: "Extracting min takes O(1), but bubbling down the root element (heapify) takes O(log N) time proportional to heap height.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Heaps",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-032",
    category: PrepCategory.DSA,
    question: "What is the primary algorithm used to detect a cycle in a singly linked list in O(1) auxiliary space?",
    options: ["Dijkstra's Algorithm", "Floyd's Tortoise and Hare (Slow & Fast Pointer)", "Tarjan's Algorithm", "Kruskal's Algorithm"],
    correctOptionIndex: 1,
    explanation: "Floyd's cycle-finding algorithm uses two pointers moving at speed 1 and 2 respectively; if a cycle exists, they will meet in O(N) time with O(1) space.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Linked Lists",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-033",
    category: PrepCategory.DSA,
    question: "Which sorting algorithm achieves stable sorting with guaranteed O(N log N) worst-case time complexity?",
    options: ["QuickSort", "HeapSort", "MergeSort", "SelectionSort"],
    correctOptionIndex: 2,
    explanation: "MergeSort is a divide-and-conquer algorithm that guarantees O(N log N) in all cases (best, average, worst) and preserves relative order of equal keys (stable).",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Sorting Algorithms",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-034",
    category: PrepCategory.DSA,
    question: "What data structure does Breadth-First Search (BFS) on an unweighted graph utilize to explore nodes level-by-level?",
    options: ["Priority Queue", "FIFO Queue", "Stack", "Disjoint Set Union (DSU)"],
    correctOptionIndex: 1,
    explanation: "BFS visits nodes in order of their distance from the source using a standard FIFO queue.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Graphs",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-035",
    category: PrepCategory.DSA,
    question: "In the 0/1 Knapsack problem with N items and capacity W, what is the standard 2D dynamic programming time and space complexity?",
    options: ["O(2^N) time, O(1) space", "O(N * W) time, O(N * W) space", "O(N log W) time, O(W) space", "O(N + W) time, O(1) space"],
    correctOptionIndex: 1,
    explanation: "The state is dp[i][w], iterating over N items and W capacity units, resulting in pseudo-polynomial O(N * W) time and space.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Dynamic Programming",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-036",
    category: PrepCategory.DSA,
    question: "What is the average and worst-case time complexity of lookup in a Hash Table with separate chaining?",
    options: ["Average O(1), Worst O(N)", "Average O(log N), Worst O(N)", "Average O(1), Worst O(1)", "Average O(N), Worst O(N^2)"],
    correctOptionIndex: 0,
    explanation: "Average hash distribution yields O(1) access; if all keys hash to the same bucket (hash collision attack), it degrades to linear search O(N).",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Hashing",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-037",
    category: PrepCategory.DSA,
    question: "Dijkstra's shortest path algorithm fails or produces incorrect results when the graph contains:",
    options: ["Directed edges", "Cycles", "Negative edge weights", "Disconnected components"],
    correctOptionIndex: 2,
    explanation: "Dijkstra's greedy assumption assumes adding edges can only increase path distance. Negative weights invalidate this; Bellman-Ford must be used instead.",
    difficulty: QuestionDifficulty.HARD,
    topic: "Graph Algorithms",
    marks: 3,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-038",
    category: PrepCategory.DSA,
    question: "What is the minimum number of binary comparisons required in the worst-case to sort 5 items using comparison-based sorting?",
    options: ["5", "7", "10", "12"],
    correctOptionIndex: 1,
    explanation: "Information theoretic lower bound = ceil(log2(5!)) = ceil(log2(120)) = ceil(6.906) = 7 comparisons.",
    difficulty: QuestionDifficulty.HARD,
    topic: "Algorithm Analysis",
    marks: 3,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // --- DBMS & OPERATING SYSTEMS (8) ---
  {
    id: "pq-039",
    category: PrepCategory.DBMS,
    question: "In relational database ACID properties, which property ensures that once a transaction has committed, its changes will survive power loss or crashes?",
    options: ["Atomicity", "Consistency", "Isolation", "Durability"],
    correctOptionIndex: 3,
    explanation: "Durability guarantees that completed transactions are permanently written to non-volatile storage (via Write-Ahead Logging / WAL).",
    difficulty: QuestionDifficulty.EASY,
    topic: "Transactions & ACID",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-040",
    category: PrepCategory.DBMS,
    question: "A relation is in Boyce-Codd Normal Form (BCNF) if and only if for every non-trivial functional dependency X -> Y:",
    options: [
      "Y is a prime attribute",
      "X is a superkey",
      "X is a candidate key or Y is prime",
      "Y is a composite key",
    ],
    correctOptionIndex: 1,
    explanation: "In BCNF, the left-hand side X of every non-trivial dependency must be a superkey of the relation.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Normalization",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-041",
    category: PrepCategory.DBMS,
    question: "Why are B+ Trees favored over balanced BSTs for disk-based relational database indexes?",
    options: [
      "B+ Trees have lower fan-out and deeper depth",
      "B+ Trees have high fan-out, shallow depth, and all records are linked in leaves for sequential range scans",
      "B+ Trees require zero memory locks",
      "B+ Trees store full table records in internal routing nodes",
    ],
    correctOptionIndex: 1,
    explanation: "High fan-out minimizes costly disk I/O seek operations, and leaf pointer linkages allow high-throughput range scans.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Indexing & Storage",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-042",
    category: PrepCategory.DBMS,
    question: "Which SQL isolation level prevents Dirty Reads, Non-repeatable Reads, and Phantom Reads completely?",
    options: ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
    correctOptionIndex: 3,
    explanation: "Serializable is the highest ANSI SQL isolation level, preventing all three concurrency anomalies by serializing access.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Transaction Isolation",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-043",
    category: PrepCategory.OPERATING_SYSTEMS,
    question: "Which of the following conditions is NOT one of Coffman's four necessary conditions for deadlock in operating systems?",
    options: ["Mutual Exclusion", "Hold and Wait", "Preemption", "Circular Wait"],
    correctOptionIndex: 2,
    explanation: "The condition is NO PREEMPTION (resources cannot be forcibly taken from a process). Preemption prevents deadlocks.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Deadlocks",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-044",
    category: PrepCategory.OPERATING_SYSTEMS,
    question: "What hardware component caches recent virtual-to-physical address translations to accelerate paging?",
    options: ["Translation Lookaside Buffer (TLB)", "Instruction Register (IR)", "Direct Memory Access (DMA)", "Program Counter (PC)"],
    correctOptionIndex: 0,
    explanation: "The TLB is an associative MMU cache storing recent page-table lookups, avoiding multi-level memory lookups on TLB hits.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Virtual Memory",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-045",
    category: PrepCategory.OPERATING_SYSTEMS,
    question: "Belady's Anomaly (where increasing the number of page frames leads to an increase in page faults) can occur in which page replacement algorithm?",
    options: ["Least Recently Used (LRU)", "Optimal Page Replacement (OPT)", "First In First Out (FIFO)", "Least Frequently Used (LFU)"],
    correctOptionIndex: 2,
    explanation: "FIFO is not a stack-based algorithm, making it vulnerable to Belady's Anomaly where more physical frames yield more page faults.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Page Replacement",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-046",
    category: PrepCategory.OPERATING_SYSTEMS,
    question: "What is the primary difference between a process and a thread in modern operating systems?",
    options: [
      "Threads have separate virtual address spaces, while processes share address space",
      "Processes have isolated address spaces, while threads within the same process share code, data, and open file handles",
      "Threads cannot perform system calls",
      "Processes cannot communicate via IPC",
    ],
    correctOptionIndex: 1,
    explanation: "A thread is a lightweight unit of CPU execution sharing memory and resources with sibling threads inside the parent process.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Processes & Concurrency",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // --- PROGRAMMING & OOP (6) ---
  {
    id: "pq-047",
    category: PrepCategory.PROGRAMMING,
    question: "In Object-Oriented Programming, dynamic polymorphism (runtime method overriding) is typically implemented via:",
    options: ["Virtual Method Table (vtable)", "Preprocessor macros", "Compiler inlining", "Static linking"],
    correctOptionIndex: 0,
    explanation: "Compilers generate a vtable containing pointers to virtual member functions, resolving the concrete method at runtime based on the object's dynamic type.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "OOP Concepts",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-048",
    category: PrepCategory.PROGRAMMING,
    question: "What does the JavaScript event loop do when the call stack is empty?",
    options: [
      "Terminates the program immediately",
      "Picks the first task from the microtask queue (e.g. Promises) before processing macrotasks (e.g. setTimeout)",
      "Executes all setTimeout timers first",
      "Clears browser memory cache",
    ],
    correctOptionIndex: 1,
    explanation: "Microtasks (resolved Promise callbacks, queueMicrotask) have higher priority and drain completely before the next macrotask is dequeued.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "JavaScript Runtime",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-049",
    category: PrepCategory.PROGRAMMING,
    question: "In C++, what happens when a base class pointer deletes a derived class object without a virtual destructor?",
    options: [
      "Derived class destructor is called correctly",
      "Undefined behavior / partial destruction (derived destructor never executes, causing memory leaks)",
      "Compilation error",
      "Automatic garbage collection",
    ],
    correctOptionIndex: 1,
    explanation: "Without a virtual destructor in the base class, deleting via base pointer invokes only the base destructor, leaking derived resources.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "C++ Memory Management",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-050",
    category: PrepCategory.PROGRAMMING,
    question: "What is the core principle behind the 'L' in SOLID design principles (Liskov Substitution Principle)?",
    options: [
      "Classes should have one reason to change",
      "Objects of a superclass should be replaceable with objects of its subclasses without breaking program correctness",
      "High-level modules should not depend on low-level modules",
      "Clients should not be forced to depend upon interfaces that they do not use",
    ],
    correctOptionIndex: 1,
    explanation: "LSP states that subtype objects must behave in a way that does not violate any expectations established by the supertype.",
    difficulty: QuestionDifficulty.MEDIUM,
    topic: "Design Principles",
    marks: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-051",
    category: PrepCategory.HR_INTERVIEW,
    question: "In the STAR technique for answering behavioral interview questions, what do the letters stand for?",
    options: [
      "Strategy, Technique, Analysis, Resolution",
      "Situation, Task, Action, Result",
      "Strength, Teamwork, Aptitude, Readiness",
      "System, Time, Architecture, Reflection",
    ],
    correctOptionIndex: 1,
    explanation: "STAR stands for Situation (context), Task (challenge), Action (steps taken), and Result (outcomes and metrics achieved).",
    difficulty: QuestionDifficulty.EASY,
    topic: "Behavioral Interviews",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "pq-052",
    category: PrepCategory.COMPANY_SPECIFIC,
    question: "Which Google engineering leadership principle emphasizes writing clean, testable code that anticipates scale and failures?",
    options: [
      "Always Ship Faster than Customers Ask",
      "Design for Scale and Graceful Degradation",
      "Avoid Refactoring Legacy Code",
      "Focus Only on Immediate Sprint Targets",
    ],
    correctOptionIndex: 1,
    explanation: "Google engineering culture strongly mandates designing for 10x scale, high test coverage, and automated graceful degradation under load.",
    difficulty: QuestionDifficulty.EASY,
    topic: "Company Cultures",
    marks: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

// ==========================================
// 8 DEMO QUIZZES
// ==========================================
export const DEMO_QUIZZES: DemoQuiz[] = [
  {
    id: "qz-001",
    title: "General Aptitude Diagnostic Test",
    slug: "general-aptitude-diagnostic",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    durationSeconds: 1200, // 20 minutes
    questionCount: 10,
    totalMarks: 16,
    passingMarks: 10,
    status: QuizStatus.PUBLISHED,
    questionIds: [
      "pq-001", "pq-002", "pq-003", "pq-004", "pq-005",
      "pq-006", "pq-007", "pq-008", "pq-009", "pq-010"
    ],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-15T09:00:00.000Z",
    updatedAt: "2026-01-15T09:00:00.000Z",
  },
  {
    id: "qz-002",
    title: "Logical & Analytical Reasoning Sprint",
    slug: "logical-reasoning-sprint",
    category: PrepCategory.LOGICAL_REASONING,
    durationSeconds: 900, // 15 minutes
    questionCount: 10,
    totalMarks: 16,
    passingMarks: 10,
    status: QuizStatus.PUBLISHED,
    questionIds: [
      "pq-011", "pq-012", "pq-013", "pq-014", "pq-015",
      "pq-016", "pq-017", "pq-018", "pq-019", "pq-020"
    ],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-16T10:00:00.000Z",
    updatedAt: "2026-01-16T10:00:00.000Z",
  },
  {
    id: "qz-003",
    title: "Verbal Ability & Grammar Benchmark",
    slug: "verbal-ability-benchmark",
    category: PrepCategory.VERBAL_ABILITY,
    durationSeconds: 600, // 10 minutes
    questionCount: 8,
    totalMarks: 11,
    passingMarks: 7,
    status: QuizStatus.PUBLISHED,
    questionIds: [
      "pq-021", "pq-022", "pq-023", "pq-024",
      "pq-025", "pq-026", "pq-027", "pq-028"
    ],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-17T11:00:00.000Z",
    updatedAt: "2026-01-17T11:00:00.000Z",
  },
  {
    id: "qz-004",
    title: "Data Structures & Algorithms Assessment",
    slug: "dsa-technical-assessment",
    category: PrepCategory.DSA,
    durationSeconds: 1500, // 25 minutes
    questionCount: 10,
    totalMarks: 19,
    passingMarks: 12,
    status: QuizStatus.PUBLISHED,
    questionIds: [
      "pq-029", "pq-030", "pq-031", "pq-032", "pq-033",
      "pq-034", "pq-035", "pq-036", "pq-037", "pq-038"
    ],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-18T10:00:00.000Z",
    updatedAt: "2026-01-18T10:00:00.000Z",
  },
  {
    id: "qz-005",
    title: "DBMS & Operating Systems Core Quiz",
    slug: "dbms-os-core-challenge",
    category: PrepCategory.DBMS,
    durationSeconds: 900, // 15 minutes
    questionCount: 8,
    totalMarks: 13,
    passingMarks: 8,
    status: QuizStatus.PUBLISHED,
    questionIds: [
      "pq-039", "pq-040", "pq-041", "pq-042",
      "pq-043", "pq-044", "pq-045", "pq-046"
    ],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-19T14:00:00.000Z",
    updatedAt: "2026-01-19T14:00:00.000Z",
  },
  {
    id: "qz-006",
    title: "Software Engineering & Clean Code Principles",
    slug: "swe-clean-code-principles",
    category: PrepCategory.PROGRAMMING,
    durationSeconds: 600, // 10 minutes
    questionCount: 6,
    totalMarks: 10,
    passingMarks: 6,
    status: QuizStatus.PUBLISHED,
    questionIds: [
      "pq-047", "pq-048", "pq-049", "pq-050", "pq-051", "pq-052"
    ],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-20T11:00:00.000Z",
    updatedAt: "2026-01-20T11:00:00.000Z",
  },
  {
    id: "qz-007",
    title: "Comprehensive Mock Placement Test (Tier 1)",
    slug: "comprehensive-mock-tier-1",
    category: PrepCategory.QUANTITATIVE_APTITUDE,
    durationSeconds: 1800, // 30 minutes
    questionCount: 12,
    totalMarks: 20,
    passingMarks: 14,
    status: QuizStatus.PUBLISHED,
    questionIds: [
      "pq-001", "pq-003", "pq-005", "pq-011", "pq-013",
      "pq-021", "pq-022", "pq-029", "pq-031", "pq-035",
      "pq-039", "pq-043"
    ],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-21T09:00:00.000Z",
    updatedAt: "2026-01-21T09:00:00.000Z",
  },
  {
    id: "qz-008",
    title: "Upcoming AI & System Design Screener",
    slug: "upcoming-ai-system-design",
    category: PrepCategory.PROGRAMMING,
    durationSeconds: 1200,
    questionCount: 4,
    totalMarks: 10,
    passingMarks: 6,
    status: QuizStatus.DRAFT, // Draft quiz hidden from students
    questionIds: ["pq-047", "pq-048", "pq-049", "pq-050"],
    createdBy: "demo-placement-001",
    createdAt: "2026-01-22T10:00:00.000Z",
    updatedAt: "2026-01-22T10:00:00.000Z",
  },
];

// Pre-seeded completed attempt for demo student
export const DEMO_QUIZ_ATTEMPTS: DemoQuizAttempt[] = [
  {
    id: "att-001",
    quizId: "qz-003",
    quizTitle: "Verbal Ability & Grammar Benchmark",
    quizCategory: PrepCategory.VERBAL_ABILITY,
    studentId: "STU-2022-0101",
    studentUserId: "demo-student-001",
    studentName: "Aarav Mehta",
    status: AttemptStatus.SUBMITTED,
    startedAt: "2026-02-01T10:00:00.000Z",
    expiresAt: "2026-02-01T10:10:00.000Z",
    submittedAt: "2026-02-01T10:07:30.000Z",
    score: 10,
    percentage: 90.9,
    passed: true,
    totalCorrect: 7,
    totalIncorrect: 1,
    totalUnanswered: 0,
    timeTakenSeconds: 450,
    answers: {
      "pq-021": 0,
      "pq-022": 1,
      "pq-023": 1,
      "pq-024": 1,
      "pq-025": 1,
      "pq-026": 0,
      "pq-027": 0,
      "pq-028": 0, // Incorrect choice for demonstration
    },
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-02-01T10:07:30.000Z",
  },
];

// In-memory runtime persistent stores
export const DEMO_COMPANIES_STORE = [...DEMO_COMPANIES];
export const DEMO_DRIVES_STORE = [...DEMO_DRIVES];
export const DEMO_APPLICATIONS_STORE = [...DEMO_APPLICATIONS];
export const DEMO_PREP_QUESTIONS_STORE = [...DEMO_PREP_QUESTIONS];
export const DEMO_QUIZZES_STORE = [...DEMO_QUIZZES];
export const DEMO_QUIZ_ATTEMPTS_STORE = [...DEMO_QUIZ_ATTEMPTS];

export function resetDemoPlacementsStore() {
  DEMO_COMPANIES_STORE.length = 0;
  DEMO_COMPANIES_STORE.push(...JSON.parse(JSON.stringify(DEMO_COMPANIES)));

  DEMO_DRIVES_STORE.length = 0;
  DEMO_DRIVES_STORE.push(...JSON.parse(JSON.stringify(DEMO_DRIVES)));

  DEMO_APPLICATIONS_STORE.length = 0;
  DEMO_APPLICATIONS_STORE.push(...JSON.parse(JSON.stringify(DEMO_APPLICATIONS)));

  DEMO_PREP_QUESTIONS_STORE.length = 0;
  DEMO_PREP_QUESTIONS_STORE.push(...JSON.parse(JSON.stringify(DEMO_PREP_QUESTIONS)));

  DEMO_QUIZZES_STORE.length = 0;
  DEMO_QUIZZES_STORE.push(...JSON.parse(JSON.stringify(DEMO_QUIZZES)));

  DEMO_QUIZ_ATTEMPTS_STORE.length = 0;
  DEMO_QUIZ_ATTEMPTS_STORE.push(...JSON.parse(JSON.stringify(DEMO_QUIZ_ATTEMPTS)));
}

